// <auto-generated />
using System;
using AttendaceManagementSystemWebAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AttendaceManagementSystemWebAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230409060310_initialcreate")]
    partial class initialcreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AttendaceManagementSystemWebAPI.Models.AttendanceLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AttendanceLogStateId")
                        .HasColumnType("int");

                    b.Property<int>("AttendanceLogStatusId")
                        .HasColumnType("int");

                    b.Property<int>("AttendanceLogTypeId")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("ImageName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TimeLog")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AttendanceLogStateId");

                    b.HasIndex("AttendanceLogStatusId");

                    b.HasIndex("AttendanceLogTypeId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("AttendanceLogs");
                });

            modelBuilder.Entity("AttendaceManagementSystemWebAPI.Models.AttendanceLogState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AttendanceLogStates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Early"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Late"
                        },
                        new
                        {
                            Id = 3,
                            Name = "N/A"
                        });
                });

            modelBuilder.Entity("AttendaceManagementSystemWebAPI.Models.AttendanceLogStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AttendanceLogStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Present"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Absent"
                        });
                });

            modelBuilder.Entity("AttendaceManagementSystemWebAPI.Models.AttendanceLogType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AttendanceLogTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "TimeIn"
                        },
                        new
                        {
                            Id = 2,
                            Name = "TimeOut"
                        });
                });

            modelBuilder.Entity("AttendaceManagementSystemWebAPI.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AccessToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeIdNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeRoleId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilePictureImageName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ResetPasswordExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("ResetPasswordToken")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeRoleId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EmailAddress = "Admin",
                            EmployeeIdNumber = "Admin",
                            EmployeeRoleId = 1,
                            FirstName = "Admin",
                            LastName = "Admin",
                            MiddleName = "",
                            Password = "8jrD2qqFoxCnkHZuU5/hjyKfN0DqsFvxkdgIr2Wf3oc=",
                            ProfilePictureImageName = "default_image.jpg",
                            RefreshTokenExpiryTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResetPasswordExpiry = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("AttendaceManagementSystemWebAPI.Models.EmployeeRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EmployeeRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "User"
                        });
                });

            modelBuilder.Entity("AttendaceManagementSystemWebAPI.Models.AttendanceLog", b =>
                {
                    b.HasOne("AttendaceManagementSystemWebAPI.Models.AttendanceLogState", "AttendanceLogState")
                        .WithMany("AttendanceLogs")
                        .HasForeignKey("AttendanceLogStateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AttendaceManagementSystemWebAPI.Models.AttendanceLogStatus", "AttendanceLogStatus")
                        .WithMany("AttendanceLogs")
                        .HasForeignKey("AttendanceLogStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AttendaceManagementSystemWebAPI.Models.AttendanceLogType", "AttendanceLogType")
                        .WithMany("AttendanceLogs")
                        .HasForeignKey("AttendanceLogTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AttendaceManagementSystemWebAPI.Models.Employee", "Employee")
                        .WithMany("AttendanceLogs")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AttendanceLogState");

                    b.Navigation("AttendanceLogStatus");

                    b.Navigation("AttendanceLogType");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("AttendaceManagementSystemWebAPI.Models.Employee", b =>
                {
                    b.HasOne("AttendaceManagementSystemWebAPI.Models.EmployeeRole", "EmployeeRole")
                        .WithMany("Employees")
                        .HasForeignKey("EmployeeRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmployeeRole");
                });

            modelBuilder.Entity("AttendaceManagementSystemWebAPI.Models.AttendanceLogState", b =>
                {
                    b.Navigation("AttendanceLogs");
                });

            modelBuilder.Entity("AttendaceManagementSystemWebAPI.Models.AttendanceLogStatus", b =>
                {
                    b.Navigation("AttendanceLogs");
                });

            modelBuilder.Entity("AttendaceManagementSystemWebAPI.Models.AttendanceLogType", b =>
                {
                    b.Navigation("AttendanceLogs");
                });

            modelBuilder.Entity("AttendaceManagementSystemWebAPI.Models.Employee", b =>
                {
                    b.Navigation("AttendanceLogs");
                });

            modelBuilder.Entity("AttendaceManagementSystemWebAPI.Models.EmployeeRole", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
